# Generated by Django 4.2.1 on 2023-05-22 14:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompilationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpuUsage', models.DurationField()),
                ('wallTime', models.DurationField()),
                ('maxMemoryBytes', models.PositiveIntegerField()),
                ('verdict', models.CharField(choices=[('OK', 'Ok'), ('WT', 'Wall time limit'), ('TL', 'Time limit'), ('ML', 'Memory limit')], max_length=2)),
                ('exitStatus_type', models.CharField(choices=[('E', 'Exited'), ('S', 'Signaled')], max_length=1)),
                ('exitStatus_code', models.SmallIntegerField()),
                ('errorLog', models.CharField(max_length=64)),
                ('binaryId', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execId', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('EN', 'Enqueued'), ('RU', 'Running'), ('OK', 'OK'), ('UN', 'Unknown')], default='EN', max_length=2)),
                ('sourceFile', models.CharField(max_length=64)),
                ('nextCheck', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('compilationResult', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.compilationresult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
