# Generated by Django 4.2.1 on 2023-05-22 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='sourceFile',
            new_name='sourceId',
        ),
    ]
