# Generated by Django 4.2.1 on 2023-05-22 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_sourcefile_submission_sourceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compilationresult',
            name='binaryId',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='submission',
            name='nextCheck',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('EN', 'Enqueued'), ('RU', 'Running'), ('FI', 'Finished'), ('UN', 'Unknown')], default='EN', max_length=2),
        ),
        migrations.AlterField(
            model_name='submission',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
